import {
  CompletionContext,
  CompletionResult,
  Completion,
} from "@codemirror/autocomplete";

const BUILTINS: Completion[] = [
  "abs",
  "all",
  "any",
  "ascii",
  "bin",
  "bool",
  "breakpoint",
  "bytearray",
  "bytes",
  "callable",
  "chr",
  "classmethod",
  "compile",
  "complex",
  "copyright",
  "credits",
  "delattr",
  "dict",
  "dir",
  "divmod",
  "enumerate",
  "eval",
  "exec",
  "filter",
  "float",
  "format",
  "frozenset",
  "getattr",
  "globals",
  "hasattr",
  "hash",
  "help",
  "hex",
  "id",
  "input",
  "int",
  "isinstance",
  "issubclass",
  "iter",
  "len",
  "license",
  "list",
  "locals",
  "map",
  "max",
  "memoryview",
  "min",
  "next",
  "object",
  "oct",
  "open",
  "ord",
  "pow",
  "print",
  "property",
  "quit",
  "range",
  "repr",
  "reversed",
  "round",
  "set",
  "setattr",
  "slice",
  "sorted",
  "staticmethod",
  "str",
  "sum",
  "super",
  "tuple",
  "type",
  "vars",
  "zip",
].map((label) => ({ label, type: "function" }));

const KEYWORDS: Completion[] = [
  "False",
  "None",
  "True",
  "and",
  "as",
  "assert",
  "async",
  "await",
  "break",
  "class",
  "continue",
  "def",
  "del",
  "elif",
  "else",
  "except",
  "finally",
  "for",
  "from",
  "global",
  "if",
  "import",
  "in",
  "is",
  "lambda",
  "nonlocal",
  "not",
  "or",
  "pass",
  "raise",
  "return",
  "try",
  "while",
  "with",
  "yield",
].map((label) => ({ label, type: "keyword" }));

const STDLIB_MODULES: Completion[] = [
  "math",
  "os",
  "sys",
  "re",
  "json",
  "datetime",
  "time",
  "random",
  "collections",
  "itertools",
  "functools",
  "pathlib",
  "typing",
  "string",
  "io",
  "copy",
  "pprint",
  "traceback",
  "threading",
  "dataclasses",
  "enum",
  "abc",
  "operator",
  "struct",
  "hashlib",
  "base64",
  "urllib",
  "http",
  "csv",
  "sqlite3",
  "logging",
].map((label) => ({ label, type: "namespace" }));

const MATH_ATTRS: Completion[] = [
  "math.pi",
  "math.e",
  "math.tau",
  "math.inf",
  "math.nan",
  "math.sqrt",
  "math.floor",
  "math.ceil",
  "math.fabs",
  "math.factorial",
  "math.gcd",
  "math.lcm",
  "math.log",
  "math.log2",
  "math.log10",
  "math.exp",
  "math.pow",
  "math.sin",
  "math.cos",
  "math.tan",
  "math.asin",
  "math.acos",
  "math.atan",
  "math.atan2",
  "math.degrees",
  "math.radians",
  "math.hypot",
  "math.isfinite",
  "math.isinf",
  "math.isnan",
].map((label) => ({ label, type: "variable" }));

const ALL_COMPLETIONS = [
  ...KEYWORDS,
  ...BUILTINS,
  ...STDLIB_MODULES,
  ...MATH_ATTRS,
];

export function pythonCompletions(
  context: CompletionContext,
): CompletionResult | null {
  const word = context.matchBefore(/[\w.]+/);
  if (!word || (word.from === word.to && !context.explicit)) return null;

  const text = word.text;
  const filtered = ALL_COMPLETIONS.filter((c) =>
    c.label.toLowerCase().startsWith(text.toLowerCase()),
  );

  if (filtered.length === 0) return null;

  return {
    from: word.from,
    options: filtered,
    validFor: /^[\w.]*$/,
  };
}
