import {
  CompletionContext,
  CompletionResult,
  Completion,
} from "@codemirror/autocomplete";

const KEYWORDS: Completion[] = [
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "null",
  "of",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "undefined",
  "var",
  "void",
  "while",
  "yield",
  "async",
  "await",
].map((label) => ({ label, type: "keyword" }));

const GLOBALS: Completion[] = [
  "console",
  "Math",
  "JSON",
  "Date",
  "Array",
  "Object",
  "String",
  "Number",
  "Boolean",
  "RegExp",
  "Error",
  "Promise",
  "Set",
  "Map",
  "WeakMap",
  "WeakSet",
  "Symbol",
  "Proxy",
  "Reflect",
  "parseInt",
  "parseFloat",
  "isNaN",
  "isFinite",
  "encodeURIComponent",
  "decodeURIComponent",
  "encodeURI",
  "decodeURI",
  "setTimeout",
  "clearTimeout",
  "setInterval",
  "clearInterval",
  "structuredClone",
  "globalThis",
  "Infinity",
  "NaN",
  "undefined",
].map((label) => ({ label, type: "variable" }));

const CONSOLE_METHODS: Completion[] = [
  "console.log",
  "console.error",
  "console.warn",
  "console.info",
  "console.dir",
  "console.table",
  "console.time",
  "console.timeEnd",
  "console.count",
  "console.group",
  "console.groupEnd",
  "console.clear",
].map((label) => ({ label, type: "function" }));

const MATH_METHODS: Completion[] = [
  "Math.abs",
  "Math.ceil",
  "Math.floor",
  "Math.round",
  "Math.max",
  "Math.min",
  "Math.pow",
  "Math.sqrt",
  "Math.cbrt",
  "Math.log",
  "Math.log2",
  "Math.log10",
  "Math.exp",
  "Math.sin",
  "Math.cos",
  "Math.tan",
  "Math.asin",
  "Math.acos",
  "Math.atan",
  "Math.atan2",
  "Math.random",
  "Math.sign",
  "Math.trunc",
  "Math.hypot",
  "Math.PI",
  "Math.E",
  "Math.LN2",
  "Math.LN10",
].map((label) => ({ label, type: "variable" }));

const ARRAY_METHODS: Completion[] = [
  "Array.from",
  "Array.isArray",
  "Array.of",
  ".map",
  ".filter",
  ".reduce",
  ".forEach",
  ".find",
  ".findIndex",
  ".some",
  ".every",
  ".includes",
  ".indexOf",
  ".push",
  ".pop",
  ".shift",
  ".unshift",
  ".splice",
  ".slice",
  ".concat",
  ".join",
  ".reverse",
  ".sort",
  ".flat",
  ".flatMap",
  ".fill",
  ".at",
  ".keys",
  ".values",
  ".entries",
].map((label) => ({ label, type: "method" }));

const JSON_METHODS: Completion[] = ["JSON.parse", "JSON.stringify"].map(
  (label) => ({ label, type: "function" }),
);

const OBJECT_METHODS: Completion[] = [
  "Object.keys",
  "Object.values",
  "Object.entries",
  "Object.assign",
  "Object.freeze",
  "Object.create",
  "Object.fromEntries",
  "Object.getOwnPropertyNames",
  "Object.hasOwn",
].map((label) => ({ label, type: "function" }));

const ALL = [
  ...KEYWORDS,
  ...GLOBALS,
  ...CONSOLE_METHODS,
  ...MATH_METHODS,
  ...ARRAY_METHODS,
  ...JSON_METHODS,
  ...OBJECT_METHODS,
];

export function jsCompletions(
  context: CompletionContext,
): CompletionResult | null {
  const word = context.matchBefore(/[\w.]+/);
  if (!word || (word.from === word.to && !context.explicit)) return null;

  const text = word.text.toLowerCase();
  const filtered = ALL.filter((c) => c.label.toLowerCase().startsWith(text));
  if (filtered.length === 0) return null;

  return { from: word.from, options: filtered, validFor: /^[\w.]*$/ };
}
